### ISSUE TITLE
failure when skipping a test

### ISSUE THREAD

**Issue by GabyCT** [bats-core/bats-core#292] opened 2020-04-27 20:33 UTC
Using the latest bats version 1.2.0, I got a failure even if I am skipping a test, for example,
https://github.com/kata-containers/tests/blob/master/integration/docker-compose/docker-compose.bats
I do
```
$ bats docker-compose.bats
1..1
# bats warning: Executed 0 instead of expected 1 tests
```
however, if I check the exit code
```
$ echo $?
1
```

**Comment by sublimino** [comment] 2020-04-28 07:51
Hi @GabyCT, thanks for the report. 

Can you confirm you're using `master` instead of the `v1.2.0` tag please?

With v1.1.0:
- with `skip` in setup, teardown, and test: `1 test, 0 failures`, exit 0
- with `skip` in test only: `1 test, 0 failures, 1 skipped`, exit 0

With v1.2.0
- with `skip` in setup, teardown, and test: `1 test, 0 failures, 1 not run`, exit 0
- with `skip` in test only: `1 test, 0 failures, 1 skipped`, exit 0

With master
- with `skip` in setup, teardown, and test: `bats warning: Executed 0 instead of expected 1 tests` and `1 test, 0 failures, 1 not run`, exit 1
- with `skip` in test only: `1 test, 0 failures, 1 skipped`, exit 0

So it looks like Bats is now failing non-zero if the `skip` is executed from the `setup` and/or `teardown` methods, rather than the actual `@test`. I guess this is somewhere is the https://github.com/bats-core/bats-core/pull/246 and https://github.com/bats-core/bats-core/pull/244 merges, have you got any idea please @martin-schulze-vireso?

**Comment by martin-schulze-vireso** [comment] 2020-04-28 11:23
The error stems from the test count validator. I refactored this code to ease implementation with the parallel execution mode.
The validator parses through the tap output before the formatter and counts the number of tests. When the test is skipped in setup, no output line is generated so it cannot be counted.

**Comment by sublimino** [comment] 2020-04-28 11:34
Aha, I guess the difference here is that the test count validator is now a fatal error, which wasn't a known change on my behalf. 

Shall we back out the breaking change, open an issue to discuss, and proceed from there @martin-schulze-vireso? Or will that break parts of the implementation of #244?

**Comment by martin-schulze-vireso** [comment] 2020-04-28 11:36
No, that is orthogonal. I think it would be trivial to return to the old behavior of just issuing a warning and listing the difference as not run.

**Comment by sublimino** [comment] 2020-04-28 11:59
@martin-schulze-vireso  apologies, I meant the section of the breaking change (specifically the fatal error), not the whole change. Agree with your approach.

If we can restore the old behaviour that would be preferable. Yes, found that `teardown() { skip; }` is the problem here too. If you want to start a draft PR I can contribute, or happy to review when done 🙏

**Comment by sublimino** [comment] 2020-04-28 12:04
`issue-292/skip-in-setup-and-teardown.bats`:

```bash
#!/usr/bin/env bats

setup () {
	skip "This is not working (https://github.com/kata-containers/runtime/issues/175)"
}

@test "skip in teardown" {
  true
}

teardown() {
	skip "This is not working (https://github.com/clearcontainers/runtime/issues/1042)"
}
```

`issue-292/skip-in-setup.bats`:

```bash
#!/usr/bin/env bats

setup () {
	skip "This is not working (https://github.com/kata-containers/runtime/issues/175)"
}

@test "skip in setup" {
  :
}
```

`issue-292/skip-in-test.bats`:

```bash
#!/usr/bin/env bats

@test "skip in test" {
	skip "This is not working (https://github.com/clearcontainers/runtime/issues/1042)"
}
```

`issue-292/skip-in-teardowm.bats`:

```bash
#!/usr/bin/env bats

@test "skip in teardown" {
  true
}

teardown() {
	skip "This is not working (https://github.com/clearcontainers/runtime/issues/1042)"
}
```

Output

```bash
1..4
ok 2 skip in setup # skip This is not working (https://github.com/kata-containers/runtime/issues/175)
not ok 3 skip in teardown
# (from function `teardown' in test file test/acceptance/skip-in-teardown.bats, line 7)
#   `teardown() {' failed
ok 4 skip in test # skip This is not working (https://github.com/clearcontainers/runtime/issues/1042)
# bats warning: Executed 3 instead of expected 4 tests
```

**Comment by martin-schulze-vireso** [comment] 2020-04-28 12:09
@sublimino Do you have a branch with that reproducer ready? That seems a good start for me.

**Comment by sublimino** [comment] 2020-04-28 12:12
@martin-schulze-vireso

Pushed to https://github.com/bats-core/bats-core/commit/84bacd02fec053111ea96022628fa8b4bb6556e5

I think this shows:
- where there is a `skip` in both `setup` and a `teardown`, the test is marked as not executed (if the skip is just in `setup` the test is correctly skipped)
- where there's a `skip` in `teardown` that function fails
- tests marked as not executed return fatal error

**Comment by martin-schulze-vireso** [comment] 2020-04-28 12:15
I just compared the v1.2.0 code and saw that they also return non zero when they issue the mismatch. However, their count does not fail on the teardown skipped test.

My assumption is that the exit traps interact badly with the exit in skip. We probably need a special skip function for teardown in this case.

**Comment by martin-schulze-vireso** [comment] 2020-04-28 12:26
@sublimino On a side node: What is the expected behavior when setup is skipped? Does teardown even make sense in this case?

**Comment by sublimino** [comment] 2020-04-28 12:42
> What is the expected behavior when setup is skipped? Does teardown even make sense in this case?

Great point, I don't know. I'd guess sticking as close to the documentation is probably best:

> Note: setup and teardown hooks still run for skipped tests.

So then `skip` in a `teardown` could `skip` the suite if it's not already skipped, and just `return` if it's already skipped?

**Comment by martin-schulze-vireso** [comment] 2020-04-28 12:51
> > Note: setup and teardown hooks still run for skipped tests.
> 
> So then skip in a teardown could skip the suite if it's not already skipped, and just return if it's already skipped?

That is very few text to interpret. I'd read that as only describing the skip function inside tests. Obviously, there are people who also use it in setup/teardown. I don't know how large their codebase is so it might not be feasible to change the behavior here.

If I could wish I would opt for following behavior:

- skip in setup skips setup, test and teardown, maybe does not even count the test but at least will not mark as failed
- skip in test runs setup and teardown and will mark the test as ok (unless teardown failed I guess?)
- skip in teardown does not change the test's result, because it has already run, but skips the remaining code within teardown (somewhat like return) and gives a warning to use return instead of skip in teardown

**Comment by sublimino** [comment] 2020-04-28 13:30
I agree with the bullets, but I think the first one is a breaking change?

The second is desired, and current state I think.

The third is breaking too I think, but is very edge/undefined behaviour and I agree should be defined. 

How about we implement 2 and 3, get it tested in master before the next release, and review 1 with consumers on a dedicated issue?

**Comment by martin-schulze-vireso** [comment] 2020-04-28 14:05
I am fine with that approach. The idea of skipping teardown from setup was to reduce the number of different cases in the 3bit (skip in setup/test/teardown) matrix.

**Comment by GabyCT** [comment] 2020-04-28 14:19
@sublimino yes, I was using master

**Comment by sublimino** [comment] 2020-04-28 21:37
@GabyCT @martin-schulze-vireso has just merged a fix for this in https://github.com/bats-core/bats-core/pull/296. Using your example code the output is now error-free:

```bash
$ bats ./docker-compose.bats
 - run REDIS application (skipped: This is not working (https://github.com/kata-containers/runtime/issues/175))

1 test, 0 failures, 1 skipped

$ echo $?
0
```

Please test and let us know how you get on : ]

**Comment by GabyCT** [comment] 2020-04-29 14:53
@sublimino thanks for everything, I build bats from master and then installed it and then I ran my test and now is working
```
$ bats docker-compose.bats
1..1
ok 1 run REDIS application # skip This is not working (https://github.com/kata-containers/runtime/issues/175)
$ echo $?
0
$ bats --version
Bats 1.2.0
```

**Closed** 2020-04-29 16:05 UTC
