### ISSUE TITLE
bats-format-junit: line 86: name: unbound variable

### ISSUE THREAD

**Issue by vasudev0529** [bats-core/bats-core#629] opened 2022-08-09 18:41 UTC
Hi ,

I am trying to use the submodules of bats-core repo and when trying to take the junit report, it is getting failed with the below error.

```
./../../../submodules/bats/bin/bats -F junit ./ > <my_dir>
<mydir>/submodules/bats/libexec/bats-core/bats-format-junit: line 86: name: unbound variable
<mydir>/submodules/bats/libexec/bats-core/bats-format-junit: line 86: name: unbound variable
```

below is the bats-core submodule being used,

git submodule
 dd2d573a803d6f9c9b004cc91ca6028b884e5ac3  ../../../submodules/bats (v1.7.0-114-gdd2d573)

As a workaround, tried changing the code from set -euo pipefail to set -eo pipefail in bats/libexec/bats-core/bats-format-junit . Not sure if that is right, please guide me here

**Comment by martin-schulze-vireso** [comment] 2022-08-09 18:58
Since you are using submodules could you try the current master? I have merged some fixes for unbound variables.

**Comment by vasudev0529** [comment] 2022-08-10 03:58
> Since you are using submodules could you try the current master? I have merged some fixes for unbound variables recently.

I think as per the commit shared in the log, am using the latest commit of the master branch. Is that what you are saying or could you please elaborate a bit

**Comment by martin-schulze-vireso** [comment] 2022-08-10 06:35
Oh, I read that as you we're using v1.7.0. can you give a reproducer?

**Comment by vasudev0529** [comment] 2022-08-10 06:54
I am trying to create junit report in xml format and redirecting that junit xml report to my dir as shared below.

```
./../../../submodules/bats/bin/bats -F junit ./ > <my_dir>
<mydir>/submodules/bats/libexec/bats-core/bats-format-junit: line 86: name: unbound variable
<mydir>/submodules/bats/libexec/bats-core/bats-format-junit: line 86: name: unbound variable
```

**Comment by martin-schulze-vireso** [comment] 2022-08-10 07:31
I already saw that in your OP. However, there are tests in place that should check for this exact problem so there must be something special about your setup that triggers the error. Can post what the command produces with `-F cat`?

**Comment by martin-schulze-vireso** [comment] 2022-08-10 22:21
I think I can reproduce the output when having an error in `setup_file()`. This would have become more obvious with the output shown. As you stated that you want a report file, I would recommend you to use `--report-formatter junit` instead of `-F`+redirect. This leaves the stdout for pretty output.

**Comment by vasudev0529** [comment] 2022-08-11 04:12
@martin-schulze-vireso 

thanks martin, if I include the above commit it would work?, 

tried with --report-formatter junit but still the same response..

$ ./../../../submodules/bats/bin/bats --report-formatter junit ./ > $RESULT_DIR_ROOT/${INFRA_ENV}_report.xml
/home/gitlab-runner/builds/TGZ15sk7/0/tec/gitlab/soshinkai-ngp/cloud-pos/infrastructure/infra-test-step1/submodules/bats/libexec/bats-core/bats-format-junit: line 86: name: unbound variable
/home/gitlab-runner/builds/TGZ15sk7/0/tec/gitlab/soshinkai-ngp/cloud-pos/infrastructure/infra-test-step1/submodules/bats/libexec/bats-core/bats-format-junit: line 86: name: unbound variable

**Comment by martin-schulze-vireso** [comment] 2022-08-12 21:45
> $ `bats --report-formatter junit ./ > {INFRA_ENV}_report.xml`

No need to redirect the output when you are using `--report-formatter`. It will generate a file in the specified format for you (by default `./report.xml`. The commit should introduce a fix but more importantly, you can work around that by fixing your code. If you had not redirected the output, you would see an error message that indicates the problem: an error in `setup_file`. If you resolve this, you won't run into this problem in the first place.

**Closed** 2022-08-15 10:49 UTC
Labels: Type: Bug, Priority: Medium, Component: Bash Code, Status: Confirmed
