### ISSUE TITLE
Weird behaviour when mocking functions with launchctl

### ISSUE THREAD

**Issue by javierspn** [bats-core/bats-core#566] opened 2022-04-21 05:43 UTC
**Describe the bug**
When we mock calls to launchctl to load or unload certain services, bats reports it to be executed X+a random number of times when it shall be just X times.

**To Reproduce**
1. Create the mock
2. Execute bats

**Expected behavior**
If we mock launchctl running in the function 3 times it shall be called just 3 times

**Environment (please complete the following information):**
 - Bats Version 1.5.0
 - OS: MacOS
 - Bash 5.1

**Additional context**
Hi team,

I have this function:

```
function stop_appx_services {
    /bin/launchctl unload /Library/LaunchDaemons/com.appx.driver.plist
    /bin/launchctl unload /Library/LaunchDaemons/com.appxy.cod.plist
    /bin/launchctl unload /Library/LaunchDaemons/com.appxz.cod.ens.plist
    /bin/sleep 10
    declare -i counter
    counter="$(/bin/ps -A | /usr/bin/grep 'appx\|appxy\|appxz' | /usr/bin/wc -l)"

    if [ "$counter" -gt 1 ]; then
        return 1
    else
        return 0
    fi
}
```
And this test for it:
```
{ # stop_appx_services
    @test 'stop_appx_services: Correct calls' {
        mock_launchctl="$(mock_create)"
        function /bin/launchctl { $mock_launchctl $@; }

        mock_ps="$(mock_create)"
        function /bin/ps { $mock_ps; }

        mock_grep="$(mock_create)"
        function /usr/bin/grep { $mock_grep $@; }

        mock_wc="$(mock_create)"
        function /usr/bin/wc { $mock_wc $@; }

        run stop_collector_services

        assert_success
        assert_output ''

        # assert_equal "$(mock_get_call_num ${mock_launchctl})"
        # assert_equal "$(mock_get_call_args ${mock_launchctl} 1)" 'unload /Library/LaunchDaemons/com.appx.driver.plist'
        # assert_equal "$(mock_get_call_args ${mock_launchctl} 2)" 'unload  /Library/LaunchDaemons/com.appxy.cod.plist'
        # assert_equal "$(mock_get_call_args ${mock_launchctl} 3)" 'unload /Library/LaunchDaemons/com.appxz.cod.ens.plist'

        assert_equal "$(mock_get_call_num ${mock_ps})" 1
        assert_equal "$(mock_get_call_args ${mock_ps})" '-A'

        assert_equal "$(mock_get_call_num ${mock_grep})" 1
        assert_equal "$(mock_get_call_args ${mock_grep})" 'appx\|appxy\|appxz'

        assert_equal "$(mock_get_call_num ${mock_wc})" 1
        assert_equal "$(mock_get_call_args ${mock_wc})" '-l'
    }
}
```
The thing is, whenever I execute bats, it says in essence that launchctl is executed more than 3 times:
```
     `assert_equal "$(mock_get_call_num ${mock_launchctl})" 5' failed
   
   -- values do not equal --
   expected : 5
   actual   : 4
   --
```
Even more, if I comment out all launchctl assert calls the following mock:
```
     `assert_equal "$(mock_get_call_num ${mock_ps})" 1' failed
   
   -- values do not equal --
   expected : 1
   actual   : 4
```

Weird behaviour, I wonder if it has to do with launchctl itself?

Thanks!

**Comment by martin-schulze-vireso** [comment] 2022-04-21 16:01
This is not the full test file, right? Could you provide a complete reproducer?

Also, what does the complete tap output look like?

**Comment by martin-schulze-vireso** [comment] 2022-06-04 06:20
Since I could not reproduce this, I will close this issue if there is no further feedback.

**Comment by martin-schulze-vireso** [comment] 2022-06-05 21:11
Please feel free to reopen with new information.

**Closed by martin-schulze-vireso** 2022-06-05 21:11 UTC
Labels: Type: Bug, Status: Unconfirmend, Component: Bash Code, Waiting for Contributor Feedback, Priority: NeedsTriage
