### ISSUE TITLE
Test 66 "Don't hang on CTRL-C (issue #353)" produces hundreds of "DEBUG warning" lines

### ISSUE THREAD

**Issue by gioele** [bats-core/bats-core#655] opened 2022-09-18 08:56 UTC
**Describe the bug**

In versions 1.7.0 and 1.8.0, test 66 "Don't hang on CTRL-C (issue #353)" produces hundreds of `DEBUG warning` lines, when run on a recent Debian amd64 sid system.

> ```
> ok 65 each file is evaluated n+1 times
> not ok 66 Don't hang on CTRL-C (issue #353)
> # (in test file test/bats.bats, line 673)
> #   `[[ $status -ne 0 ]] \' failed
> # 1..1
> # not ok 1 test
> # # (in test file test/fixtures/bats/hang_in_test.bats, line 7)
> # #   `sleep 10' failed with status 130
> # # /<<PKGBUILDDIR>>/lib/bats-core/tracing.bash: line 43: DEBUG warning: wait_for: recursively setting old_sigint_handler to wait_sigint_handler: running_trap = 1
> # # /<<PKGBUILDDIR>>/lib/bats-core/common.bash: line 3: DEBUG warning: mark_dead_jobs_as_notified: ndead (0) != js.j_ndead (1)
> # # /<<PKGBUILDDIR>>/lib/bats-core/common.bash: line 3: DEBUG warning: mark_dead_jobs_as_notified: ndead (0) != js.j_ndead (1)
> # # /<<PKGBUILDDIR>>/lib/bats-core/common.bash: line 3: DEBUG warning: mark_dead_jobs_as_notified: ndead (0) != js.j_ndead (1)
> ```

You can see a full log at <http://qa-logs.debian.net/2022/09/17/bats_1.7.0-0.1_unstable.log>.

**To Reproduce**

1. `docker run --rm -it -v /tmp/d debian:sid`
2. `apt update && apt install git`
4. `cd /tmp && git clone https://github.com/bats-core/bats-core && cd bats-core`
5. `mkdir -p ~/.parallel && touch ~/.parallel/will-cite`
6. `bin/bats --tap test`

**Expected behavior**

Test 66 should not produce any `DEBUG` line.

**Environment (please complete the following information):**
 - Bats Version 1.7.0 and 1.8.0
 - OS: Debian sid amd64
 - Bash version: 5.2.0(1)-rc2

**Additional context**

EDIT: A previous version of this report misrepresented the issue, saying that the test was hanging. A more careful reading of the logs shows that only test 73 "CTRL-C aborts and fails the current test" hangs (reported in #654).

**Comment by martin-schulze-vireso** [comment] 2022-09-18 11:34
I am closing this as a duplicate of the other issue (#654).

**Closed by martin-schulze-vireso** 2022-09-18 11:34 UTC
Labels: Type: Bug, Priority: NeedsTriage
