### ISSUE TITLE
Debian 10 installation not working OOTB

### ISSUE THREAD

**Issue by ghost** [bats-core/bats-core#371] opened 2020-10-25 13:42 UTC
I posted on Gitter, but there doesn't look like there is much activity over there.  After installing with Linuxbrew or installing it from the source code, I get the same errors, albeit the line number is different for Linuxbrew.  The below error is repeated for each test in the *pyenv* project, which is the reason why I installed bats.
___
Command I am using is: `bats $HOME/pyenv/test`

Error message:

```bash
/usr/local/libexec/bats-core/bats-exec-file: line 242: bats-exec-test: command not found
/usr/local/libexec/bats-core/bats-exec-file: line 242: bats-exec-test: command not found
/usr/local/libexec/bats-core/bats-exec-file: line 242: bats-exec-test: command not found
/usr/local/libexec/bats-core/bats-exec-file: line 242: bats-exec-test: command not found
/usr/local/libexec/bats-core/bats-exec-file: line 242: bats-exec-test: command not found
   bats warning: Executed 0 instead of expected 174 tests

174 tests, 0 failures, 174 not run
```
___
**Additional info**

bats-core location:
```zsh
➜  pyenv (master) ✗) which bats
/usr/local/bin/bats
```

bats executable search:
```zsh
(master)⚡)% ls /usr/local/bin | grep bats
bats
```

**Comment by bromps** [comment] 2020-10-25 16:24
I'm getting the same issue with Homebrew on macOS Catalina 10.15.7 as well.

**Comment by bromps** [comment] 2020-10-25 16:56
Copying the rest of the executables to the `/usr/local/bin` directory does the trick.  However, I would think that the main `bats` executable would be smart enough to find the libexec files.

```
sudo cp /usr/local/Cellar/bats-core/1.2.1/libexec/bats-core/bats-* /usr/local/bin
```

**Comment by martin-schulze-vireso** [comment] 2020-10-25 19:17
Thanks for trying gitter first.

Could you give the exact steps you took for installing on each of the platforms?

I just tried `brew install bats-core` and got 1.2.1 where I cannot reproduce this issue with a simple test file.

**Comment by martin-schulze-vireso** [comment] 2020-10-25 19:23
I can reproduce with pyenv. On closer inspection their `test/` contains a `libexec/`. Maybe that messes up something within bats? 1.2.1 is the first version with exec-file which sources the scripts before running them, so they might mess up internal state.

**Comment by bromps** [comment] 2020-10-25 20:20
Ah, good catch.  Since you were able to reproduce with pyenv, but not in other projects, I'm going to open an issue in that repo.  Thanks for looking into this.

**Comment by martin-schulze-vireso** [comment] 2020-10-25 20:40
Hm, it depends whether we want to support such use cases or not. I think this problem highlights an issue with the current approach: Broken test scripts can trip up the bats run.

The only reason for `source`ing the test file in bats-exec-file right now is: to inherit exported variables from setup_file in the test. Maybe we can let the users tell us which variables to forward and put the actual evaluation into its own shell, so it does not trip up the rest of the execution.

**Comment by bromps** [comment] 2020-10-27 04:43
I'm all for building more resilience into tooling.  If you could add something to the backlog to address this issue that would be appreciated.

**Comment by martin-schulze-vireso** [comment] 2021-04-25 12:53
I am closing this in favor of #418 .

**Closed by martin-schulze-vireso** 2021-04-25 12:53 UTC
