### ISSUE TITLE
Just ... THANKS

### ISSUE THREAD

**Issue by cavo789** [bats-core/bats-core#576] opened 2022-05-06 12:16 UTC
This message is to thank you for developing and maintaining bats-core.  For some time now, I have been maintaining a library with bash scripts and helpers that can be reused in multiple projects and, thanks to bats, I am guaranteed not to break anything when I refactor. 

At this point I have almost 400 tests and if they all pass, I can merge my development branch with a main branch without too much fear. It's really comfortable too, **thanks for your work!**

**Comment by martin-schulze-vireso** [comment] 2022-05-07 08:21
Let me thank you for your kind words on behalf of the whole @bats-core/bats-core team. It is always nice to see our work bear fruit and hear back from the community.

I'll leave this issue open for a bit to give others the chance to chip in.

**Comment by fmorency** [comment] 2022-06-13 17:12
+1! Thanks a lot for all your work!

**Comment by mmetc** [comment] 2022-06-17 09:57
Thank you for keeping this alive. I have been using bats a few years ago so I knew where to go with the functional tests for a new project. A quick survey confirmed me that it's still the best option, and getting better.

**Comment by ChaosZh** [comment] 2022-08-03 06:15
+1 Bats really drag me out of my messy bash code. Thanks for your excellent work!

**Comment by jkroepke** [comment] 2022-08-21 07:35
Thanks from my side, too. With bats, I have the possibility to maintain my shell script project without breaking things. It helps a lot, even to find new bugs by just adding tests.

**Comment by martin-schulze-vireso** [comment] 2023-02-27 22:01
This issue stayed open a bit longer than I intended and I think it has served its purpose, so I am closing it now.

Thanks again for the kind feedback. :heart:

**Closed by martin-schulze-vireso** 2023-02-27 22:01 UTC
