### ISSUE TITLE
skip (conditional):  skip counter not getting incremented for skipped tests

### ISSUE THREAD

**Issue by git4lad** [bats-core/bats-core#264] opened 2020-03-03 18:20 UTC
I do have 2 tests one which has conditional skip and one has unconditional skip. 
Some how i don't see counter getting incremented for conditional skip and it shows skip = 0 if i run conditional skip test.

Do we know if its existing issue ? 

Tried on latest cloned code.  Bats 1.2.0-dev

**Comment by martin-schulze-vireso** [comment] 2020-11-02 22:51
Sorry for letting this lie around so long. I have seen other issues with skips, so it might be related but it has been a while.
Anyhow, I cannot reproduce this with current master, so I am closing this as it might be out of date.

Feel free to reopen this, if you can reproduce it with current master. Please also provide a short reproducer (.bats test file + call) and exact version information.

**Closed by martin-schulze-vireso** 2020-11-02 22:51 UTC
