### ISSUE TITLE
Maintainers + access update!

### ISSUE THREAD

**Issue by btamayo** [bats-core/bats-core#4] opened 2017-09-24 16:52 UTC
Hello all,

Since one of the main goals of this move is to prevent lock-out by giving access to more than one person, I thought that that would be apt to prioritize. 

My decision is to pick **three additional people** that will be able to have admin access to this repository based on the following criteria: 
1. Knowledge/usage about bats and/or bash
2. Recent Activity on GitHub (if they've been online recently)
3. Expressed interest in the original [Call For Maintainers thread](https://github.com/sstephenson/bats/issues/150)

### Responsibilities
The main responsibility here is to be active and prevent lock-out. It doesn't necessarily mean that we will change existing processes, but it does mean that if, at some point, none of us can maintain the repo or merge PRs, one of us will have the authority and access to pass on the ability to do so.

That being said, the first order(s) of business (to which everyone/anyone can contribute towards) will be:
1. Finish moving PRs and issues to this org
2. Organize docs/tests
3. Finish issues in [#196](https://github.com/sstephenson/bats/issues/196)

### Why three people?
Too many chefs spoil the broth, etc etc. But people should have access to the broth. :) 

### Who?
The following folks will be asked to help but they need to express interest (if they're not active on GitHub at all there wouldn't be much of a point):
1. @ztombol
2. ~~@mbland~~ ✅ 
3. ~~@jasonkarns~~ ✅ 

Since things could have changed for them (no longer interested, time commitments, etc.) please let me know if you're interested in helping maintain through this thread :)

**Comment by mbland** [comment] 2017-09-25 12:50
I'm in. I've just started a new job, but Bash and Bats are tools I'm planning on using and spreading heavily here, so this shouldn't stretch me too thin, especially if you and others will help spread the load a bit. Thanks for doing this!

**Comment by sublimino** [comment] 2017-09-25 17:08
I'm willing to help - not got a lot of time but love this project/BASH, and use both widely, so can be of use.

**Comment by btamayo** [comment] 2017-09-26 04:11
@mbland I appreciate it! No worries. Right now I just want to make sure people don't get locked out then we can figure out the rest of the logistics :) 

@sublimino Thank you! That will help a ton -- we're still figuring out things right now so we might take you up on that offer sooner/later!

**Comment by jasonkarns** [comment] 2017-10-02 13:35
@btamayo i'm in!

**Comment by jasonkarns** [comment] 2017-10-02 16:26
Myself and @agent-0028 have been going through the [roadmap](https://github.com/sstephenson/bats/issues/196) to verify PRs are good to go. We were assuming that the best way to move forward was to open duplicate PRs for each one listed in the roadmap against this repo. However, it appears that since this repo was not opened as a "fork" of sstephenson/bats, the PRs cannot be trivially opened. (ie, we would need to create a fork of bats-core before we could open the PR, rather than just having a single fork of bats, and simply adding bats-core as an additional remote).

Are there any concerns with submitted a request to github that this repo be tied as a fork of bats? (At least temporarily until/if bats itself is migrated to an org?)

**Comment by mbland** [comment] 2017-10-02 16:32
No particular concern on my part, but if that isn't feasible, we could ping the threads and ask the authors to rebase their changes on our `master` branch and re-submit the PRs here. Or we could do it.

Perhaps we should port the roadmap over here, too.

**Comment by jasonkarns** [comment] 2017-10-02 18:11
@agent-0028 and I are spending our @testdouble Ship-It! day on bats-* tasks, so we're mostly reviewing PRs from the roadmap and re-submitting them here. We've already re-forked from bats-core, so there isn't really an issue for us any longer. Perhaps this won't even matter at all soon.

The concern isn't so much about rebasing onto this master, but rather that github doesn't allow opening PRs from a sstephenson/bats fork against this repo. It requires the PR author first fork from bats-core before opening the PR.

Github support has been willing to _remove_ the fork connection between repos in the past. I'm just hoping/assuming they can do the reverse and _connect_ two repos as a fork. I think the request would need to come from someone in the org. (And I only just this morning confirmed my willingness to join the org, so I'm not yet a member.)

**Comment by btamayo** [comment] 2017-10-27 02:20
@jasonkarns @mbland Oof. Wrote up a reply (over email) to this which was never sent. 

I didn't realize that GitHub has been willing to remove fork connections in the past. That might have given me additional pause. I opted for a mirror because I thought the dependency on a separate upstream wasn't really ideal, and being a fork also wasn't ideal for visibility (i.e. search). Getting the best of both worlds (the repointing of the PRs and the shared histories, etc) would have been great, though. At the end I thought that people forking an outdated repo, PRing to it, and creating new PRs off the same version would be a bit messy -- and I thought it was best to clean things up as best we can, then accept new PRs or compatible PRs. 

We could probably create a quick guide for those that wish to repoint their PRs to a non-fork, but I also have no real qualms about being tied as a fork as long as it doesn't introduce the concerns I had above (search and upstream dependency).

**Comment by jasonkarns** [comment] 2017-10-30 12:16
I contacted them and apparently they can't make it a fork after the repo has been created. (besides nuking repo and forking)

**Comment by Potherca** [comment] 2018-01-20 20:00
@jasonkarns If there are still PR's from `sstephenson/bats` that you'd want here, I don't mind putting in the work to make it possible.

The most straightforward way would be:
- Create a single for from `bats-core/bats-core`
- Use the  `.patch` feature github offers to create a patch from each MR
- Create a separate branch on the fork for each PR
- Apply the patch
- Open an MR here from each separate branch of the fork

That way the original author does not need to be involved but they are still given credit.

Optionally a comment could be added to each MR on `sstephenson/bats` to ask/inform the original author of their code being applied here (if permission to use the MR code is an issue... I don't know as [IANAL](https://en.wikipedia.org/wiki/IANAL)).

**Comment by jasonkarns** [comment] 2018-06-12 15:14
I think we can close this now? (Though pinging @ztombol again for their interest.)

**Closed by jasonkarns** 2018-06-12 15:14 UTC
Labels: META-NEWS

**Comment by scontini76** [comment] 2019-01-26 09:34
I see very low activity on this so useful project, there are manu bugs around and a lot of pull request quite neglected... Is it just a bad moment for maintainers or the project is going to stasis state? Can someone reassure the many users of this project? If it's just my feelings, just don't care and pardon me!

**Comment by Potherca** [comment] 2019-01-27 12:44
Well... There have been over 250 commits since this project forked of from the original (dead) BATS repo. Various MRs have been merged during the last few months of last year and questions/issues have been responded to by maintainers and/or core contributors during the ladt few days.

It is not uncommon to see less activity on open-source projects during December an January, as both work and family life become more demanding during those months. (The same goes for July/August/September). 

If you look at w hat _is_ being done, as oposed to what is not being done, I don't think there is much to worry about yet. Not untill there has been *no* activity whatsover from core members for at least six months.
