### ISSUE TITLE
Executed 0 instead of 1 expected tests

### ISSUE THREAD

**Issue by jaxxstorm** [bats-core/bats-core#364] opened 2020-10-07 00:48 UTC
I have a really really simple setup:

my `foo.sh`
```
#!/bin/sh
foo()
{
  echo "foo"
}
```

my `foo.bats`

```
#!/usr/bin/env bats

setup() {
    source foo.sh
}

@test "foo" {
  run foo
  [ "$status" -eq 0 ]
}
```

No matter what i seem to do, I get the following output:

```
bats warning: Executed 0 instead of expected 1 tests  
```

What's missing here?

**Comment by martin-schulze-vireso** [comment] 2020-10-07 06:50
I cannot reproduce the behavior with your example. Which version of bats and bash are you using on which OS?

**Comment by martin-schulze-vireso** [comment] 2020-11-02 10:42
I am closing this as it is not reproducible and there was no further feedback.

**Closed by martin-schulze-vireso** 2020-11-02 10:42 UTC

**Comment by kzidane** [comment] 2021-04-27 16:58
@martin-schulze-vireso  I ran into a similar issue and it seemed to be caused by one of my scripts trapping `EXIT`. Is that expected behavior?

```
$ ./test/bats/bin/bats -v
Bats 1.3.0

$ cat src/foo.bash
#!/bin/bash

echo foo
trap 'echo exiting' EXIT

$ cat test/test.bats
setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'

    PROJECT_ROOT="$( cd "$( dirname "$BATS_TEST_FILENAME" )/.." >/dev/null 2>&1 && pwd )"
    source "$PROJECT_ROOT/src/foo.bash"
}

@test "should show error" {
    assert false
}

$ ./test/bats/bin/bats test/test.bats
   should show error                                                                                                                                                                                           1/1
   bats warning: Executed 0 instead of expected 1 tests

1 test, 0 failures, 1 not run
```

Removing the trap line, shows the error as expected:

```
$ cat src/foo.bash
#!/bin/bash

echo foo

$ ./test/bats/bin/bats test/test.bats
 ✗ should show error

   (from function `assert' in file test/test_helper/bats-assert/src/assert.bash, line 40,
    in test file test/test1.bats, line 10)
     `assert false' failed
   foo

   -- assertion failed --
   expression : false
   --


1 test, 1 failure
```

**Comment by martin-schulze-vireso** [comment] 2021-04-27 17:00
Yes that is expected. Bats sets up several traps to catch and report test failures.

**Comment by kzidane** [comment] 2021-04-27 17:01
@martin-schulze-vireso thanks for getting back so quickly! Is there a recommended workaround here?

**Comment by martin-schulze-vireso** [comment] 2021-04-27 17:16
I have not run into that usecase yet, so I can't recommend anything. I presume the answer depends on whether you want to retain the trap or not.

If you want to retain it for testing of its effects, I would probably run it in a subshell to prevent interference.

If you don't need it and want to test the sourced functions, I would try to deactivate the trap setup when sourced under tests. In theory you could try to restore bats' traps but I would deem that too error prone.

**Comment by rijnhard** [comment] 2022-06-14 09:32
I know I'm necro-ing this thread, but just ran across this when I called a function from a loaded file in `setup_file` that was only loaded in `setup`.

the moment I moved the load to `setup_file` then all worked

**Comment by martin-schulze-vireso** [comment] 2022-06-15 11:34
I think any error (an maybe even skip?) in setup_file will lead to this message. I found this to be rather cosmetic, so decided to use the time to fix this for other issues. If you want to, you can explain what exactly you find problematic in a new issue that references this discussion.

**Comment by rijnhard** [comment] 2022-07-29 11:40
The problem is that the output is so non-specific it gives you no guidance into what the error is...
I figured it out after 2 hours by luck.

**Comment by martin-schulze-vireso** [comment] 2022-07-29 13:35
I think you Case of calling a undefined function in setup_file should produce a meaningful error message already. Can you post a new issue with a minimal reproducer?

**Comment by edouard-lopez** [comment] 2022-12-02 12:56
In my case, it was a missing `;` (semicolon) in a test double function's body

```diff
setup() { … }

@test "can install with standard user" {
-    id() { echo foo }; export -f id # mock
+    id() { echo foo; }; export -f id # mock
}

@test "can install with root user" { … }
```
