### ISSUE TITLE
An execution mode where failures drop you into the shell environment

### ISSUE THREAD

**Issue by djmcgreal-cc** [bats-core/bats-core#667] opened 2022-10-13 16:00 UTC
**Is your feature request related to a problem? Please describe.**

Developing test issues currently means trying to replicate the shell environment outside of bats, typically by running through test cases line by line. This is fine for simple cases but can become problematic.

**Describe the solution you'd like**

I'd like to be able to execute `bats --enter-shell-on-failures` which, when run interactively, would, instead of moving onto the next test, give interactivity into the shell environment bats has been creating, allowing arbitrary bash commands to be run from this point, to e.g. inspect variables, etc.

**Comment by martin-schulze-vireso** [comment] 2022-10-13 19:05
I think this is a duplicate of #186

**Comment by djmcgreal-cc** [comment] 2022-10-13 19:10
Cool. I hadn't thought of opening a shell myself. Thanks

**Closed** 2022-10-13 19:09 UTC
Labels: Status: Duplicate, Type: Enhancement

**Comment by djmcgreal-cc** [comment] 2022-10-14 08:40
An enhancement over #189 occurs to me: being able to press a key during a long running execution and attach to the process currently running - a big ask I realise.

**Comment by martin-schulze-vireso** [comment] 2022-10-14 10:00
Please add new comments over there.
