### ISSUE TITLE
QUESTION - Stop on the first failure, is this possible? 

### ISSUE THREAD

**Issue by cavo789** [bats-core/bats-core#611] opened 2022-06-15 10:25 UTC
Hello

Just one question (I didn't find the answer right now): I'm building a Docker image and I wish to run a lot of .bats files to verify the quality of my image when built.  If one test fail (like does the docker image contains the curl binary f.i.); I wish to stop everything since I need to take action and rebuild my Docker image.

So, the question : can we stop bats as soon as one error is encountered?

A think like ` ./test/bats/bin/bats --stop-on-first-failure .` 

Thanks for any tips

**Comment by martin-schulze-vireso** [comment] 2022-06-15 11:27
This is a duplicate of #209.

**Closed** 2022-06-15 11:28 UTC
Labels: Status: Duplicate, Type: Enhancement
