### ISSUE TITLE
Possible bashisms makes tests not run

### ISSUE THREAD

**Issue by mandelmassa** [bats-core/bats-core#448] opened 2021-05-31 07:38 UTC
Hi, I'm trying to use bats-core on an embedded system with busybox, where the shell apparently doesn't support the process substitution syntax used in bats-exec-suite. Running bats results in the following error:

```
% bats .
/usr/libexec/bats-core/bats-exec-suite: line 69: /dev/fd/62: No such file or directory

0 tests, 0 failures
```

I've applied the following patch which gets around the issue enough to be able to use bats-core on my system. But unfortunately, this also isn't a correct fix since it effectively disables the duplicate test case filter functionality:

```
--- a/libexec/bats-core/bats-exec-suite
+++ b/libexec/bats-core/bats-exec-suite
@@ -73,7 +73,7 @@ for filename in "$@"; do
 
   test_names=()
   test_dupes=()
-  while read -r line; do
+  BATS_TEST_FILTER="$filter" bats-preprocess "$filename" | while read -r line; do
     if [[ ! "$line" =~ ^bats_test_function\  ]]; then
       continue
     fi
@@ -88,14 +88,14 @@ for filename in "$@"; do
       continue
     fi
     test_names+=("$line")
-  done < <(BATS_TEST_FILTER="$filter" bats-preprocess "$filename")
+  done
 
   if [[ "${#test_dupes[@]}" -ne 0 ]]; then
     abort "Duplicate test name(s) in file \"${filename}\": ${test_dupes[*]}"
   fi
 done
 
-test_count="${#all_tests[@]}"
+test_count=$(cat $TESTS_LIST_FILE | wc -l)
 
 if [[ -n "$count_only_flag" ]]; then
   printf '%d\n' "${test_count}"
@@ -130,7 +130,7 @@ export BATS_SUITE_TMPDIR
 # (see https://github.com/bats-core/bats-core/issues/329)
 # If a file was specified multiple times, we already got it repeatedly in our TESTS_LIST_FILE.
 # Thus, it suffices to bats-exec-file it once to run all repeated tests on it.
-IFS=$'\n' read -d '' -r -a  BATS_UNIQUE_TEST_FILENAMES < <(printf "%s\n" "$@"| nl | sort -k 2 | uniq -f 1 | sort -n | cut -f 2-) || true
+printf "%s\n" "$@"| nl | sort -k 2 | uniq -f 1 | sort -n | cut -f 2- | IFS=$'\n' read -d '' -r -a  BATS_UNIQUE_TEST_FILENAMES || true
 
 if [[ "$num_jobs" -gt 1 ]] && [[ -z "$bats_no_parallelize_across_files" ]]; then
   # run files in parallel to get the maximum pool of parallel tasks
@@ -144,7 +144,7 @@ if [[ "$num_jobs" -gt 1 ]] && [[ -z "$bats_no_parallelize_across_files" ]]; then
     parallel --keep-order --jobs "$num_jobs" bats-exec-file "$(printf "%q " "${flags[@]}")" "{}" "$TESTS_LIST_FILE"  ::: "${BATS_UNIQUE_TEST_FILENAMES[@]}" 2>&1 || status=1
   fi
 else
-  for filename in "${BATS_UNIQUE_TEST_FILENAMES[@]}"; do
+  for filename in "$@"; do
     bats-exec-file "${flags[@]}" "$filename" "${TESTS_LIST_FILE}" || status=1
   done
 fi
-- 
```

Regards,
Mathias

**Comment by noel-yap** [comment] 2021-06-05 17:47
I've run into a similar error (although I don't know if the cause is the same -- @mandelmassa, could you elaborate on what you did to produce the error?).

The way I got my error is through something like `bats <(some-command)`. The reason I was doing that is so that I could use a multiline shebang:
```
#!/bin/bash
git submodule update --init --remote "${WORKSPACE}/bash/bats-assert"
git submodule update --init --remote "${WORKSPACE}/bash/bats-core"
git submodule update --init --remote "${WORKSPACE}/bash/bats-support"

# Call the new script
SOURCE_DIR="$(dirname "$(realpath $0)")" \
    TEST_DIR="${tmpdir}" \
    "${WORKSPACE}/bash/bats-core/bin/bats" <(sed -e '1,/^!#$/d' $0)

exit
!#
```

**Comment by martin-schulze-vireso** [comment] 2021-06-06 09:33
> The way I got my error is through something like `bats <(some-command)`.

Please don't do that. Bats works under the assumption that it handles physical files that can be read multiple times.

> The reason I was doing that is so that I could use a multiline shebang:

This is the content of `some-command`? I am not sure what exactly you want to achieve and if this is the best approach to it. Anyways, this is likely not related to the issue above.

**Comment by mandelmassa** [comment] 2021-06-07 09:02
@noel-yap all I'm doing is running `bats .` in a directory with a simple .bats file in it

**Comment by noel-yap** [comment] 2021-06-07 13:45
@martin-schulze-vireso , `some-command` is `sed -e '1,/^!#$/d' $0`.

If `bats` needs physical files, would it be feasible for it to make its own physical copy to  use?

**Comment by martin-schulze-vireso** [comment] 2021-06-07 14:27
@noel-yap so could your Code. So gar this seema Like a niche usecase to me. If you have a compelling argument for bats to check for non physical files instead of exoecting them from you, please do so in a separate feature request issue.

**Comment by martin-schulze-vireso** [comment] 2021-06-12 07:39
@mandelmassa I am not sure if this is really a busybox problem AFAIK our Alpine container also runs busybox and does not show this problem.

**Comment by mandelmassa** [comment] 2021-06-14 07:59
@martin-schulze-vireso yes, I'm also not too sure why this could be. The unpatched bats-core works well on our 64-bit targets, but will fail with the reported error on our 32-bit targets, built from the same source and with similar configurations. Unfortunately I haven't been able to figure out what the actual issue is, but reworking the process substitutions to pipes was the simplest workaround to be able to deploy bats-core in our testing pipeline.

I realize this isn't a lot to work with, and at the end of the day I already have a working bats-core deployment. I just wanted to report this anyway even though I don't have too many clues to provide.

Thanks

**Comment by martin-schulze-vireso** [comment] 2021-07-30 09:23
@mandelmassa Can you give more detail on the environment:

- what operating system (with version)?
- which bash version?
- which busybox version?

**Comment by martin-schulze-vireso** [comment] 2021-08-14 11:44
Since there has been not feedback, I am closing this. Feel free to reopen with the requested information attached.

**Comment by mandelmassa** [comment] 2021-08-16 13:35
Hi, sorry for my late response. Here are the versions:

OS: Yocto 2.5/Sumo, Linux 4.14.115-rt59 armv7l GNU/Linux
Bash: GNU bash, version 4.4.12(1)-release (arm-poky-linux-gnueabi)
Busybox: BusyBox v1.27.2

Regards,
Mathias

**Comment by martin-schulze-vireso** [comment] 2021-09-21 12:28
Thanks for reporting this. Unfortunately, the cost/benefit ratio of this does not work out for me, as I don't have the reproducer environment around. So I am closing this until the benefit becomes larger or the cost goes down.

**Closed by martin-schulze-vireso** 2021-09-21 12:28 UTC
Labels: Type: Bug, Priority: High, Status: Unconfirmend, Component: Bash Code
