### ISSUE TITLE
Add test timing report

### ISSUE THREAD

**Issue by filmil** [bats-core/bats-core#139] opened 2018-08-14 21:46 UTC
Sometimes it is useful to know how long it took for a test case to execute.

It would be nice if bats printed this information somewhere.  I couldn't figure out if there is a standard slot in the tap report where this information would be surfaced.

**Comment by mbland** [comment] 2018-08-14 22:18
Dupe of #49, #127.

**Closed by mbland** 2018-08-14 22:18 UTC
