### ISSUE TITLE
"No such file or directory" when invoking via Windows Git Bash

### ISSUE THREAD

**Issue by NathanJAdams** [bats-core/bats-core#323] opened 2020-06-23 12:58 UTC
Installing as an npm dependency and running via an package.json script on a Windows Git Bash terminal produces a "No such file or directory" error.
It's produced because the script location is a Windows path so `cd`-ing into it won't work.
A potential bugfix would be to translate the path to a Unix path format before `cd`-ing into it.

**Comment by NathanJAdams** [comment] 2020-06-23 13:16
A temporary work-around for this is to invoke bats like the following

`bash -c 'bats <test-file.bats>' \"$(pwd)/node_modules/bats/bin/bats\"`

This allows injecting the script path in Unix format which the bats file will then pick up as normal

**Comment by sublimino** [comment] 2020-06-24 14:07
Thanks for the report @NathanJAdams. I don't have any Windows expertise, is it possible that you could add a simple failing test case to Bats, or demo it here, so that I can try a blind fix?! :D 

If you add it to bats the `--filter` flag saves running the whole suite during development, as you probably know 🙏

**Comment by NathanJAdams** [comment] 2020-07-02 11:03
Unfortunately bats fails before it gets to the stage of invoking any script.

The part it fails in is in the bats/bin/bats file here:

    if [[ "$target_dir" != "$path" ]]; then
        cd "$target_dir" #fails here as $target_dir is a Windows path, eg. C:\Users\UserName\path\to\script
    fi

**Comment by martin-schulze-vireso** [comment] 2021-04-25 13:01
Sounds like #424  is a duplicate of this?

**Comment by martin-schulze-vireso** [comment] 2021-07-23 23:26
Since we got no feedback, I am going to assume that this was a duplicate and close it.

**Closed by martin-schulze-vireso** 2021-07-23 23:26 UTC
Labels: Component: Bash Code, Priority: High, Status: Unconfirmend, Waiting for Contributor Feedback
