### ISSUE TITLE
Issue with interop between Cygwin and MSYS (Git for Windows) when locally installing bats-core

### ISSUE THREAD

**Issue by exoosh** [bats-core/bats-core#724] opened 2023-05-12 14:56 UTC
**Description**

I have installed bats-core as per the instructions, using `./install.sh $HOME` from "Git Bash" (i.e. the MSYS-based environment that ships with Git for Windows).

The outcome is that `$HOME/bin/bats` as well as the files it installs into `$HOME/libexec/bats-core` all have CRLF line endings.

The Bash that comes with Git for Windows deals with those just fine, but executing that installation from Cygwin -- which uses the same `$HOME/bin` (== `%USERPROFILE%\bin`) -- fails with:

```
$ bats .
/home/username/bin/bats: line 2: $'\r': command not found
: invalid option namebats: line 3: set: pipefail
```

**To Reproduce**

1. Use Git for Windows' Git Bash to install bats-core with `./install.sh $HOME`
2. After installation verify that it works and check that `$HOME/bin/bats` uses CRLF line endings (current behavior and probably the cause)
3. From Cygwin (64-bit) installed on the same system and up-to-date
  * If you don't otherwise point your Cygwin `$HOME` at `%USERPROFILE%`, it'll be sufficient to head to the location of `cygpath -w $HOME` (from Cygwin still) and start a command prompt
  * then create a junction point, linking Cygwin's `$HOME/bin` to `%USERPROFILE%\bin` with:
    * to use `junction bin %USERPROFILE%\bin` or `mklink /j bin %USERPROFILE%\bin`
    * ... from PowerShell you'd use `junction bin $env:USERPROFILE\bin` ...

**Expected behavior**

I expected the script and its dependencies to run without an issue and have LF ("Unix") line endings, but since they all had CRLF line endings, the script fails.

**Local workaround**

```
dos2unix "$HOME/bin/bats" "$HOME/libexec/bats-core"/bats* "$HOME/lib/bats-core"/*
```

**Environment:**
- Bats Version: `Bats 1.9.0`
- OS: Windows
    * MSYS/Git for Windows: `MINGW64_NT-10.0-19045` (via `uname -s`)
        * Bash version: `GNU bash, version 5.2.15(1)-release (x86_64-pc-msys)`
        * The following Bash-internal variables allow to tell MSYS and Cygwin apart  
          ```
          $ echo "HOSTTYPE=$HOSTTYPE MACHTYPE=$MACHTYPE OSTYPE=$OSTYPE"
          HOSTTYPE=x86_64 MACHTYPE=x86_64-pc-msys OSTYPE=msys
          ```
    * Cygwin (64-bit): `CYGWIN_NT-10.0-19045` (via `uname -s`)
        * Bash version: `GNU bash, version 5.2.15(3)-release (x86_64-pc-cygwin)`
        * The following Bash-internal variables allow to tell MSYS and Cygwin apart  
          ```
          $ echo "HOSTTYPE=$HOSTTYPE MACHTYPE=$MACHTYPE OSTYPE=$OSTYPE"
          HOSTTYPE=x86_64 MACHTYPE=x86_64-pc-cygwin OSTYPE=cygwin
          ```

**Comment by martin-schulze-vireso** [comment] 2023-05-27 20:53
I can't reproduce this right now but it sounds plausible, so let me make a guess:

Your reproduction steps start one step too late, as they do not describe how you got `./install.sh` (and probably the rest of bats) onto your machine. Did you `git clone`, did you download a release, npm, ...? 

Assuming you `git clone`d it, you can instruct `git` to use LF instead of CRLF line endings.

This repository is largely maintained on Unix systems and has all files stored in LF line ending format. If you get the files in CRLF format, that seems to be the fault of your chosen distribution channel and there is not much we can do about this.

I am closing this as invalid since it does not seem to be our responsibility. Feel free to reopen, if you disagree and have more info.

**Closed by martin-schulze-vireso** 2023-05-27 20:53 UTC
Labels: Type: Bug, Priority: Medium, Status: Unconfirmend, Component: Packaging

**Comment by exoosh** [comment] 2023-05-30 08:04
I used `git clone`, fair point that that was missing.

> Assuming you git cloned it, you can instruct git to use LF instead of CRLF line endings.

I know, the infamous `core.autocrlf` is set to `false` on all of my machines. Never understood how the VCS has any business in tampering with line endings. Also it solves a problem that has long since vanished. Except, Cygwin stubbornly insists on CRLF being unusable.

And it's fine to close this. Totally get that you don't want to fix this sort of issue.

This was also meant for those who may encounter the in the future, try a web search and _now_ won't come up empty-handed (I'd hope). The error message isn't exactly obvious, but it's a Bash error message not even a `bats-core` one. Still, it happened with `bats-core`, so I wanted to report it.

Thanks for `bats-core`!
