### ISSUE TITLE
run() makes functions not stop on errors

### ISSUE THREAD

**Issue by x-yuri** [bats-core/bats-core#815] opened 2023-11-08 12:57 UTC
**Describe the bug**
`f() { set -eu; g; h; }` Generally such function should stop after trying to execute `g`, but `run()` makes it try to run `g`, then `h`. Which is at least strange (how is this even possible?). But more importantly as things stand functions behave differently under test and in real life. Which can't be good, can it?

To make it clear it's not like I like adding `set -eu` to every function. I rather prefer to run scripts with `-eu`. So I tried to force the behaviour with `set -eu`, which failed for some reason.

I guess `run()` needs some way to take the needed shell options.

**To Reproduce**

`a.sh`:

```sh
docker run --rm -itv $PWD:/app -w /app alpine:3.18 sh -euc '
    apk add bats
    bats .
'
```

`a.bats`:

```bats
@test stop-on-error {
    . b.sh
    run f
    # f
    echo "output: ($output)"
    [ "$status" -eq 0 ]
}
```

`b.sh`:

```sh
f() {
    set -eu
    g
    h
}
```

`run f`:

```
$ sh -eu a.sh
...
1..1
not ok 1 stop-on-error
# (in test file ./a.bats, line 6)
#   `[ "$status" -eq 0 ]' failed
# output: (b.sh: line 3: g: command not found
# b.sh: line 4: h: command not found)

The following warnings were encountered during tests:
BW01: `run`'s command `f` exited with code 127, indicating 'Command not found'. Use run's return code checks, e.g. `run -127`, to fix this message.
      (from function `run' in file /usr/lib/bats-core/test_functions.bash, line 297,
       in test file ./a.bats, line 3)
```

`f`:

```
$ sh -eu a.sh
...
1..1
not ok 1 stop-on-error
# (from function `f' in file b.sh, line 3,
#  in test file ./a.bats, line 4)
#   `f' failed with status 127
# b.sh: line 3: g: command not found
```

**Expected behavior**
Stop after the first error. Unless I'm missing something.

**Environment (please complete the following information):**
 - Bats version: 1.9.0
 - operating system (including version): Alpine Linux 3.18, but I don't think it's relevant here
 - `bash --version`: 5.2.15
 - Install method: `apk add`

**Comment by x-yuri** [comment] 2023-11-08 14:45
By the way, this means if I add true at the end of the function, it'll succeed (`[ "$status" -eq 0 ]`), right?

**Comment by martin-schulze-vireso** [comment] 2023-12-18 21:31
I think this is a duplicate of #719. Feel free to reopen with more information if you think this merits a different issue.

**Closed by martin-schulze-vireso** 2023-12-18 21:31 UTC
Labels: Type: Bug, Priority: NeedsTriage

**Comment by TheHillBright** [comment] 2024-01-16 11:17
I think this is different from #719 that this regards to case where `set -e` is executed in the context of `run` while #719 only executes `set -e` at the time we `source` the script (not when we use the `run` built-in).

**Comment by TheHillBright** [comment] 2024-01-16 11:20
This seems the same as #748 though, but #748 discussion later had gone in different direction.
