### ISSUE TITLE
Failure of negated statement not caught (`! command` never fails)

### ISSUE THREAD

**Issue by ad8-bdl** [bats-core/bats-core#462] opened 2021-07-02 01:07 UTC
# Summary
Commands within a test that use bash's negation operator `!` and that should fail (e.g. `! true`) don't cause the test to fail.

If such a test just happens to be the last operation in the test, that operation's exit status will propagate through to the test's return code, and _that_ will trigger the test to fail.

A workaround is to suffix affected commands with `|| false`, e.g. `! true || false`.

# Repro

bash-5.1$ bats --version
Bats 1.3.0
bash-5.1$ bash --version
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)
bash-5.1$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1217

- bash installed via brew:
bash-5.1$ brew list --versions bash
bash 5.1.8

Bats script:
```
# not working as expected:
@test "tf1" {
  true  # test failure is incorrectly attributed to this line
  ! true
} # test fails, but only due to the failing command being the final statement

@test "tf2" {
  ! true  # test should fail here, but doesn't
  true
} # test passes (wrong)

# working as expected:
@test "tf3" {
  true
  ! true || false    # test fails at this line
} 

@test "tf4" {
  ! true || false    # test fails at this line
  true
}
```

Actual Results:
```
bash-5.1$ bats /tmp/t.bats 
 ✗ tf1
   (in test file /tmp/t.bats, line 3)
     `true  # test failure is incorrectly attributed to this line' failed
 ✓ tf2
 ✗ tf3
   (in test file /tmp/t.bats, line 15)
     `! true || false    # test fails at this line' failed
 ✗ tf4
   (in test file /tmp/t.bats, line 19)
     `! true || false    # test fails at this line' failed

4 tests, 3 failures
```

Expected results:
- all tests tf[1-4] should fail
- the failure should accurately report the failing command

**Comment by martin-schulze-vireso** [comment] 2021-07-02 08:24
Unfortunately, that seems to be the intended behavior by bash:

```
 -e      Exit immediately if a pipeline (which may consist of a single simple command), a list, or a compound command (see SHELL GRAMMAR above), exits with a non-zero sta‐
                      tus.  The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test following the
                      if or elif reserved words, part of any command executed in a && or || list except the command following the final && or ||, any command  in  a  pipeline  but  the
                      last,  or  if the command's return value is being inverted with !.
```

The ERR trap's mechanism is tightly coupled with `-e`'s behavior, so negated return values are deliberately excluded.
I see the following options going forward:

- teach the preprocessor to transform negated statements into the form `! x || false`
- document the unexpected behavior
- add a shellcheck issue for that

Another remedy might be to avoid running negated commands directly, relying instead on the `run` function. There is a PR (#367) to add return code checking to the `run` function which would alleviate this problem.

Patching the preprocesser will likely entail corner cases where it still fails and won't be trivial, so I'd like to avoid that.

**Comment by martin-schulze-vireso** [comment] 2021-07-02 08:35
I have classified this as a bug although it is intended bash behavior. I expect many users not to have enough bash/bats internals experience to deduct that using `!x` is not going to fail the test if x succeeds, so it is a broken expectation.

I think changing the meaning of this could break existing users but might also be helpful to those who fell into that trap.

**Comment by ad8-bdl** [comment] 2021-07-05 05:30
Given it's explicit bash behaviour (learned something new today!), imho it's definitely "just" a documentation issue. i.e. it'd be nice to call it out. A shellcheck check would be a major bonus!

Just created a PR for the FAQ, if that helps.

**Comment by martin-schulze-vireso** [comment] 2021-07-19 07:04
Closing thus, since the PR for our documentation has been merged. The shellcheck issue can be tracked independently.

**Closed by martin-schulze-vireso** 2021-07-19 07:04 UTC
Labels: Component: Bash Code, Priority: Critical, Status: Confirmed, Type: Bug
