### ISSUE TITLE
odd failure when using --jobs

### ISSUE THREAD

**Issue by haircommander** [bats-core/bats-core#290] opened 2020-04-27 18:56 UTC
hey folks

We are running bats in a debian container in circle CI. We've run into this problem that started this morning:
`cat: /tmp/bats-run-28189/parallel_output/1/stdout: No such file or directory`
on any bats job that runs using parallel.

Has anyone seen this error/have any idea what to do to mitigate it?

**Comment by haircommander** [comment] 2020-04-27 18:56
confirmed with bats version v1.2.0 btw

**Comment by sublimino** [comment] 2020-04-27 19:06
@haircommander thanks for the report, if I understand correctly this is only on `v1.2.0` as it started this morning? What's the docker invocation, `docker run -it ...` ?

**Comment by haircommander** [comment] 2020-04-27 19:15
hard to tell exactly. We *were* building off of master, then it started failing. We attempted to switch to v1.2.0, and it continued to fail. A fun addition is that on other branches of CI, this problem does not occur :upside_down_face: . 

Unfortunately, the set up is pretty specific to our circle instance. I couldn't find a simple reproducer starting from the container and a `docker run` command. I can, however, get someone access to a shell where the problem is occurring if they want to poke around.

**Comment by GabyCT** [comment] 2020-04-27 21:04
I am seeing the same error with the latest version

**Comment by saschagrunert** [comment] 2020-04-28 07:03
Might the issue be somewhere between those changes, since we see it since last Friday (April 24th)?
https://github.com/bats-core/bats-core/compare/433db67f0081de7f0924ca74fe4afced9df5cdfb...master

**Comment by sublimino** [comment] 2020-04-28 07:33
1. Can anybody who is building from master try `v1.2.0` please? It was released before the latest set of merges https://github.com/bats-core/bats-core/commit/73b8d2f95513207b319efe34685553b75c0b214e

1. Can anybody provide a reproduction case here please? @haircommander @GabyCT is there any way you can share the bats CLI invocation and any env/docker you are using?

1. If anybody has the time, running `git bisect` should find the source of the error ([simple guide](https://dockyard.com/blog/2016/07/26/how-to-bisect-ember))

1. > Might the issue be somewhere between [433db67...master](https://github.com/bats-core/bats-core/compare/433db67f0081de7f0924ca74fe4afced9df5cdfb...master), since we see it since last Friday (April 24th)?

    It might be, but I can't see anything obvious in there. A larger search ([1.2.0 to now](https://github.com/bats-core/bats-core/compare/73b8d2f95513207b319efe34685553b75c0b214e..master?diff=unified)) will take me a bit longer to work though.

FWIW I test with `GNU parallel 20191122` in the latest Docker image, and `GNU parallel 20161222` on my local machine.

**Comment by saschagrunert** [comment] 2020-04-28 08:12
Our failing test run can be found here:  https://app.circleci.com/pipelines/github/cri-o/cri-o/3402/workflows/626f4048-68ff-47ed-97db-d5b4e7271de5/jobs/51809

The container image used for this job is this one: quay.io/crio/crio-build-amd64-go1.14:master-1.3.5
It has been built2020-04-15T15:23:07.821322863Z on  and was using the latest master of bats.

I'll dig deeper if I get more time.

**Comment by sublimino** [comment] 2020-04-28 08:20
> Our failing test run can be found here: https://app.circleci.com/pipelines/github/cri-o/cri-o/3402/workflows/626f4048-68ff-47ed-97db-d5b4e7271de5/jobs/51809
> 
> The container image used for this job is this one: quay.io/crio/crio-build-amd64-go1.14:master-1.3.5

@cyphar have you seen this error before? Any insight you might have is appreciated :pray:

**Comment by GabyCT** [comment] 2020-04-28 14:25
@sublimino yes, I was building from master, here it is an example https://github.com/cri-o/cri-o/blob/master/test/test_runner.sh#L38

**Comment by cyphar** [comment] 2020-04-28 14:37
I'm pretty sure the issue is in the JUnit formatting patches, which (among many other changes) modified how parallelism works fairly significantly. Most notably, the whole `parallel_output` path code was added in that patch. I think the issue is that the path is simply not created by the test runner...

/cc @martin-schulze-vireso

**Comment by martin-schulze-vireso** [comment] 2020-04-28 20:35
@cyphar I agree that the `mkdir parallel_output` seems to be missing. However, I wonder why this has not popped up during development. There are tests for `--jobs` and they did not fail. I noticed a peculiar pattern in the error messages from the circle-ci run above: The numbers in the error messages are not consecutive. Their spacing reflects the number of tests in each tested file, so it looks like the error happens on every first test of the respective file.

These are the indices of the failures: 1, 2, 4, 10, 12, ...

These are the number of tests in the files: 1, 2, 6, 2, ...

So far I was not able to reproduce this with a simple example.

**Comment by martin-schulze-vireso** [comment] 2020-04-28 21:07
@haircommander
> confirmed with bats version v1.2.0 btw

Can you double check that please? I think it can't be, because the `parallel_output` path only landed after v1.2.0. If it were on v1.2.0 we are seeing some really strange behavior

**Comment by martin-schulze-vireso** [comment] 2020-04-28 21:33
Since the junit PR we do parallelization via semaphores instead of the default way. Semaphores work via files in `~/.parallel/semaphore`. I just tested to run `bats --jobs 2 some_test.bats` under a user without write permissions to that folder and could reproduce the error message. 

@haircommander  Can you verify whether your CI user has a write acces to their `~/.parallel/semaphore` path in the failing test?

**Comment by sublimino** [comment] 2020-04-28 21:43
I've found some unusual behaviour in the `/tmp/` director @martin-schulze-vireso :
- test always pass in Docker build (Dockerfile in this repo)
- tests are now failing on my local machine (`Debian testing`, `Linux x 5.5.0-2-amd64 #1 SMP Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux`, `LANG=en_GB.UTF-8`)
- I have write access to `~/.parallel/semaphores/`

Invoked with
```bash
$ bin/bats --no-tempdir-cleanup test/ --filter 'parallel suite execution with --jobs'
```

Then in another window I'm inspecting the filesystem:
```bash
$ tree /tmp/bats-run-*/parallel_output/
/tmp/bats-run-533637/parallel_output/
├── 1                                                                                                                         
├── 10                                                                                                                        
│   └── \257<\257>                                                                                                            
│       └── 1                                                                                                                 
│           └── \0                                                                                                            
│               ├── seq                                                                                                       
│               ├── stderr                                                                                                    
│               └── stdout                                                                                                    
├── 11                                                                                                                        
├── 12                                                                                                                        
│   └── \257<\257>                                                                                                            
│       └── 1                                                                                                                 
│           └── \0                                                                                                            
│               ├── seq                                                                                                       
│               ├── stderr                                                                                                    
│               └── stdout                                                                                                    
```

(some of the jobs aren't started, I presume)

Could anybody else on this thread try the same?

**Comment by martin-schulze-vireso** [comment] 2020-04-28 21:55
@sublimino That looks weird. I just installed parallel version 20200422 on my host (Arch Linux 5.6.7-arch1-1) and got following output for your example call:
```
$ tree /tmp/bats-run-*/parallel_output
/tmp/bats-run-313799/parallel_output
├── 1
│   ├── seq
│   ├── stderr
│   └── stdout
├── 10
│   ├── seq
│   ├── stderr
│   └── stdout
├── 11
│   ├── seq
│   ├── stderr
│   └── stdout
├── 12
│   ├── seq
│   ├── stderr
│   └── stdout
```

Is your output stable over multiple invocations? Does the test fail?

**Comment by martin-schulze-vireso** [comment] 2020-04-28 22:09
@sublimino Could you try the code in #297 on your system?

**Comment by sublimino** [comment] 2020-04-29 12:15
@martin-schulze-vireso I still get the same error, it must be something with my local configuration. At least the parallel tests are now failing on my local machine. I'm happy to merge this to fix the errors in consumers' CI, and work on my own problem out of band!

**Comment by sublimino** [comment] 2020-04-29 12:26
@GabyCT @saschagrunert can you confirm that the fix in https://github.com/bats-core/bats-core/pull/297 (https://github.com/bats-core/bats-core/commit/0deffccf9c501f5627731acd93bbd776c8c8e292) works for you please? Thank you to @haircommander for already confirming.

**Comment by saschagrunert** [comment] 2020-04-29 14:03
@sublimino this seems to re-introduce the issue if I test the latest bats master in our CI: https://app.circleci.com/pipelines/github/openSUSE/cri-o/2717/workflows/43e23b44-425a-4522-82a2-f7bd22dd6a3e/jobs/45507/steps

**Comment by GabyCT** [comment] 2020-04-29 15:21
@sublimino for me it works the latest bats (master) thanks
```
Ensure crio service is stopped before running the tests
Ensure docker service is stopped before running the tests
Running cri-o tests with runtime: kata-runtime
++ time bats --jobs 1 --tap ctr.bats
1..46
ok 1 ctr not found correct error message
ok 2 ctr termination reason Completed

````

**Comment by sublimino** [comment] 2020-04-29 15:38
Thanks for confirming @GabyCT! It also works for @martin-schulze-vireso in Arch Linux.

@saschagrunert this also fails for me on my local machine, as `parallel` is using some funky escaping and deeper nesting than is expected. 

I think the problem may be Debian-based (I'm on Debian Buster), as I can reproduce in your CI image (also Buster). Repro case that we'll get into CI (this raises a question about distribution compatibility):

```bash
$ docker run -it quay.io/crio/crio-build-amd64-go1.14:master-1.3.7 \
    bash -c "ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts && \
      git clone https://github.com/bats-core/bats-core && \
      bats-core/bin/bats bats-core/test"  
# ...
 ✗ parallel test execution with --jobs                                                                                      
   (in test file test/parallell.bats, line 14)                                                                              
     `[ "$status" -eq 0 ]' failed                                                                                           
 ✓ parallel can preserve environment variables                                                                              
 ✗ parallel suite execution with --jobs                                                                                     
   (in test file test/parallell.bats, line 44)                                                                              
     `[ "$status" -eq 0 ]' failed                                                                                           
   1..40                                                                                                                    
   cat: /tmp/bats-run-3896/parallel_output/1/stdout: No such file or directory                                              
   cat: /tmp/bats-run-3896/parallel_output/11/stdout: No such file or directory                                             
   cat: /tmp/bats-run-3896/parallel_output/21/stdout: No such file or directory                                             
   cat: /tmp/bats-run-3896/parallel_output/31/stdout: No such file or directory                                             
   # bats warning: Executed 0 instead of expected 40 tests                                                                  
   Duration: 4                                                                                                              
 ✗ setup_file is not over parallelized                                                                                      
   (in test file test/parallell.bats, line 67)                                                                              
     `[ "$status" -eq 0 ]' failed                                                                                           
   Took 6 seconds                                                                                                           
# ...
```

I wonder if the Debian `parallel` implementation is compiled with some interesting flags...

**Comment by sublimino** [comment] 2020-04-29 16:49
@saschagrunert I'm not proud of this fix, but it's a band-aid for now https://github.com/bats-core/bats-core/pull/298

There is a difference in the way parallel is running, compiled, configured or similar in our Debian systems. Until we figure that out this bodge fix may work for you.

**Comment by martin-schulze-vireso** [comment] 2020-04-29 21:11
@sublimino Maybe the debian version behaves better with `-results parallel_output/${number}{}` which should create the files 1, 1.seq, 1.stderr instaed of a folder 1/ containing these files. Obviously, the surrounding code would have to be adapted to deal with files instead of folders.

> It also works for @martin-schulze-vireso in Arch Linux.

Just as a side note: What do you mean with "it"? My tests on Arch were done on the old code. What I mean is: I could not reproduce the error behavior on Arch. However, the fix in #297 did not break the tests on my system.

**Comment by sublimino** [comment] 2020-04-30 09:48
@martin-schulze-vireso I couldn't get any variations of that code to work, if you have a suggestion could you paste a patch in here?

> Just as a side note: What do you mean with "it"?

In the context of distribution compatibility, I meant "this code passes the test suite on Arch Linux" : ]

**Comment by sublimino** [comment] 2020-05-18 18:25
Fixes for this for Debian, and all other distributions, now in master in https://github.com/bats-core/bats-core/pull/302/files

**Closed by sublimino** 2020-05-18 18:25 UTC
